# syntax version.
version: "3.9"

services:
  web:
    image: nginx:latest
    volumes:
      - ${VOLUMES_MAIN}:/var/www:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
      - ./nginx/sites/:/etc/nginx/sites-available:ro
      - ./storage/nginx:/var/log/nginx
#      - ./nginx/config/qmyx.conf:/etc/nginx/conf.d/qmyx.conf:ro
      #- "./nginx/ssl:/etc/ssl"
#      - "/mnt/d/wamp/www/qmyx-base:/usr/share/nginx/html/qmyx-base" #需要修改为你项目的目录
    ports:
      - "80:80"  # api http
      - "443:443" # api https
    depends_on:
      - php-fpm
    restart: always
    networks:
      - default

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: divediwa
    networks:
      - default
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql

#  mariadb:
#    platform: linux/x86_64
#    container_name: mariadb
#    image: mariadb:10.3
#    ports:
#      - ${MARIADB_EXPOSE_PORT}:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
#      MARIADB_DATABASE : ${MARIADB_DATABASE}
#      MARIADB_USER: ${MARIADB_USER}
#      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
#    networks:
#      - default
#    volumes:
#      - ${MARIADB_DATA}:/var/lib/mariadb

  redis:
    image: redis:5.0.9-buster
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    stdin_open: true
    tty: true
    networks:
      - default

#  rabbitmq:
#    build: ./rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#      - "15671:15671"
#      - "15674:15674"
#    privileged: true
#    hostname: laradock-rabbitmq
#    volumes:
#      - ./storage/rabbitmq:/var/lib/rabbitmq
#      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#      - ./rabbitmq/management_agent.disable_metrics_collector.conf:/etc/rabbitmq/conf.d/management_agent.disable_metrics_collector.conf
#    depends_on:
#      - php-fcm-flow
#    networks:
#      - default

#  redis-cluster:
#    container_name: redis-cluster
#    image: grokzen/redis-cluster:latest
#    ports:
#      - "7000-7005:7000-7005"
#    networks:
#      - default

#  mongodb:
#    image: mongo:4.2
#    container_name: mongodb
#    restart: always
#    command: [--auth]
#    ports:
#      - ${MONGO_DB_PORT}:27017
#    volumes:
#      - ${MONGO_MOUNT_VOLUME}:/data/db
#      - ./dump:/dump
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
#    networks:
#      - default

  php-fpm:
    depends_on:
      - mysql
      - redis
    build:
      context: ./php-fpm
    environment:
      UPLOAD_LIMIT: 64M
    volumes:
      - ${VOLUMES_MAIN}:/var/www
      - ./php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
    tty: true
    networks:
      - default

  ftpd_server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/folder_on_disk/data:/home/username/"
      - "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
    # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
    #      - "/folder_on_disk/ssl:/etc/ssl/private/"
    # or ssl/tls with Let's Encrypt (cert and key as two files)
    #      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
    #      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
    # also for ssl/tls:
    #      ADDED_FLAGS: "--tls=2"
    restart: always
    networks:
      - default

networks:
  default:
    name: octane-backend
    driver: bridge
