# syntax version.
version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites-available:ro
      - ./storage/nginx:/var/log/nginx
#      - ./nginx/config/qmyx.conf:/etc/nginx/conf.d/qmyx.conf:ro
      #- "./nginx/ssl:/etc/ssl"
#      - "/mnt/d/wamp/www/qmyx-base:/usr/share/nginx/html/qmyx-base" #需要修改为你项目的目录
    ports:
      - "80:80"  # api http
      - "443:443" # api https
    restart: always
    networks:
      - default

  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:5.7
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ticket
    networks:
      - default
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:5.0.9-buster
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    stdin_open: true
    tty: true
    networks: 
      - default

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    command: [--auth]
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - ${MONGO_MOUNT_VOLUME}:/data/db
      - ../dump:/dump
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - default

#  ticket:
#    build:
#      context: ./php
#    container_name: ticket
#    volumes:
#      - ${VOLUMES_TICKET}:/app
#    tty: true
#    networks:
#      - default

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    depends_on:
      - mysql
    volumes:
      - ${VOLUMES_WORDPRESS}:/app
    tty: true
    networks:
      - default

  botrista:
    build:
      context: ./nodejs
    container_name: botrista
    depends_on:
      - mongodb
    volumes:
      - ${VOLUMES_BOTRISTA}:/app
    tty: true
    networks:
      - default

  sales_dashboard:
    build:
      context: ./nodejs
    container_name: sales_dashboard
    depends_on:
      - botrista
    volumes:
      - ${VOLUMES_SALES_DASHBOARD}:/app
    tty: true
    networks:
      - default

networks:
  default:
    name: octane-backend
    driver: bridge
    
