# syntax version.
version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ${VOLUMES_MAIN}:/var/www:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
      - ./nginx/sites/:/etc/nginx/sites-available:ro
      - ./storage/nginx:/var/log/nginx
#      - ./nginx/config/qmyx.conf:/etc/nginx/conf.d/qmyx.conf:ro
      #- "./nginx/ssl:/etc/ssl"
#      - "/mnt/d/wamp/www/qmyx-base:/usr/share/nginx/html/qmyx-base" #需要修改为你项目的目录
    ports:
      - "80:80"  # api http
      - "443:443" # api https
    depends_on:
      - php-fpm
    restart: always
    networks:
      - default

#  mysql:
#    platform: linux/x86_64
#    container_name: mysql
#    image: mysql:5.7
#    ports:
#      - ${MYSQL_EXPOSE_PORT}:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: ticket
#    networks:
#      - default
#    volumes:
#      - ${MYSQL_DATA}:/var/lib/mysql

  mariadb:
    platform: linux/x86_64
    container_name: mariadb
    image: mariadb:10.3
    ports:
      - ${MARIADB_EXPOSE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: file_mgm
    networks:
      - default
    volumes:
      - ${MARIADB_DATA}:/var/lib/mariadb

  redis:
    container_name: redis
    image: redis:5.0.9-buster
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    stdin_open: true
    tty: true
    networks: 
      - default

#  redis-cluster:
#    container_name: redis-cluster
#    image: grokzen/redis-cluster:latest
#    ports:
#      - "7000-7005:7000-7005"
#    networks:
#      - default

#  mongodb:
#    image: mongo:4.2
#    container_name: mongodb
#    restart: always
#    command: [--auth]
#    ports:
#      - ${MONGO_DB_PORT}:27017
#    volumes:
#      - ${MONGO_MOUNT_VOLUME}:/data/db
#      - ./dump:/dump
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
#    networks:
#      - default

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    environment:
      UPLOAD_LIMIT: 64M
    volumes:
      - ${VOLUMES_MAIN}:/var/www
      - ./php-fpm/php7.2.ini:/usr/local/etc/php/php.ini
    tty: true
    networks:
      - default

#  admin:
#    build:
#      context: ./admin
#    container_name: admin
#    volumes:
#      - ${VOLUMES_ADMIN}:/app
#    tty: true
#    networks:
#      - default

networks:
  default:
    name: octane-backend
    driver: bridge
